### PR TITLE
Refactor and Enhance UI and Functionality

### PR DESCRIPTION
**Pull request by danger-dream**
- Replaced Dropdown with tauri-plugin-context-menu for an improved context menu implementation.
- Adjusted translation window to automatically resize for better user experience.
- Simplified the styling of the translation window for a cleaner interface.
- Replaced Screenshot with capture.html to enhance screenshot and color picking functionalities.

### CODE REVIEW

**Comment by danger-dream** [comment]
Replenish：
Implemented history-based result retrieval for translations. Before translating, the system checks if there are existing results based on the text, source language, target language, and service used. If a historical result exists, it prevents redundant service calls.

**Comment by Pylogmon** [comment]
What a big PR！

I don't intend to merge this PR. Reviewing such a massive PR is too overwhelming for me. Perhaps you could consider submitting separate PRs for each feature.

Although the features you mentioned seem great, I encountered several issues during my simple testing:

- I don't really agree with what you call UI enhancement, as the readability is very poor in dark mode.
- I have no idea where you found that HTML for the new screenshot feature. Considering the entire software is implemented using React, it looks quite ugly to insert such a large HTML element.
- The software disables the context menu, but I plan to manually implement a basic context menu for copy/paste operations. There's no need to use `tauri-plugin-context-menu`. When testing on Windows, I didn't notice any difference between it and WebView's default context menu.
- The implementation of window auto-resizing is too crude and doesn't consider cases where the window exceeds the screen size.
- As for your last point about history-based functionality, I think it's excellent. You should prioritize submitting a separate pull request for this feature.

**Comment by Pylogmon** [comment]
In addition, it seems that OCR cannot be launched after taking a screenshot.

**Comment by Pylogmon** [comment]
I also noticed that you modified some default configuration items, which I do not intend to modify.

**Comment by danger-dream** [comment]
I apologize for submitting without comprehensive testing. I will submit separate PRs for the required features later.

- UI enhancement is not accurate; it's more of an adjustment. Please pull my commit and add the dark:bg-content2 style to CardHeader at [TargetArea#L304](https://github.com/danger-dream/pot-desktop/blob/master/src/window/Translate/components/TargetArea/index.jsx#L304). If you still find the style unacceptable, I will give up adjusting the UI
- My apologies for not being proficient with React. The purpose of adding that HTML was to introduce color picking functionality to the screenshot feature. I can't quite recall where this HTML came from; it's something I refactored years ago, originally offering many image editing functions like marking and mosaic that I didn't need.
- The reason for using tauri-plugin-context-menu was to fix issues with Dropdown not fully displaying when the translation window's height is insufficient and aiming for a more native appearance.
- my implementation of auto-resizing windows lacks handling for exceeding screen sizes. Adding the following code should address it:
  ```rust
  // /src/window/Translate/index.jsx#L201
  const pos = await appWindow.outerPosition()
  if (height + pos.y > monitor.size.height) {
      height = monitor.size.height - pos.y
  }
  ```
  > I'm somewhat puzzled by the different logic applied to translate_window when handling position_type=mouse: it uses the mouse position at initial launch, centers the window on the screen during text input for translation, but doesn't adjust in other scenarios. Perhaps more options should be considered?
- For history functionality, I believe it could be handled more elegantly by a dedicated module with a unified interface for service access. This is also evident in the "translate_back" feature which seems to reuse similar calls but couldn't leverage the same interface for services. Additionally, history list presentation is quite basic; ideally, there would be two lists showing original texts and Services results separately or an added search feature to avoid excessive paging when looking up content from 10 translations ago.
- The behavior after taking a screenshot should align with Screenshot/index.jsx. sending a success event after cut_image trims the picture. It's unclear why this isn't working on your end; perhaps check clip_canvas.ondblclick event in capture.html? This has been tested on Windows 10, Windows 11, and Ubuntu 22.04 without issues launching OCR.
- My modification of default configuration items was tailored to my use; it was inappropriate to include those changes in my submission—I apologize for this oversight due to late hours.
- Lastly, could you please clarify which parts should be retained or optimized? I plan to work on some things during the holiday and appreciate your guidance.

Thank you.

**Comment by Pylogmon** [comment]
Sorry, I just saw your reply. I suggest you first implement the PR related to history, and then start optimizing the function of dynamically adjusting the window size. It is recommended to pull the latest code and add some animations. If the process of adjusting the window size also has the animation couldn't be better.
As for the other few features, I don't think I want to make any changes.

Thank you for your efforts.

**Comment by Pylogmon** [comment]
I have closed this PR first and look forward to your subsequent PRs :)

**Pull request closed without merging**
