### PR TITLE
ci: update package action

### PR DESCRIPTION
**Pull request by jhongyu**

### CODE REVIEW

**Comment by Pylogmon** [comment]
Tell me Why

**Comment by jhongyu** [comment]
Currently, this workflow runs when a push is made to the `master` branch, and it's quite a time-consuming workflow. Since the main task of this workflow is to build packages and release them, it may be better to only trigger it when a release is made.

**Comment by Pylogmon** [comment]
As a cross-platform software, I have to make sure that every commit compiles successfully, so that triggering after each push is ideal. This way I can identify potential problems with other platforms in time. 
And, with each push trigger, I can also provide nightly builds between releases so that people who need them can use them in a timely manner.

**Comment by jhongyu** [comment]
Sorry for not thinking of that, I will revert the relevant changes. And since the 'checkout' job relies on git, I believe it's reasonable to place the 'checkout' job after the 'install git' job, what do you think?

**Comment by Pylogmon** [comment]
> Sorry for not thinking of that, I will revert the relevant changes. And since the 'checkout' job relies on git, I believe it's reasonable to place the 'checkout' job after the 'install git' job, what do you think?

No, The checkout action is not a simple `git clone`, it does not rely on git, I only installed git to get the version number.

**Pull request closed without merging**
